name: Build IPA

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main
  workflow_dispatch:  # 允许手动触发

jobs:
  build:
    name: Build Unsigned IPA
    runs-on: macos-14  # 使用最新的 macOS runner，支持 Xcode 15+
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.2'  # 指定 Xcode 版本
        
    - name: Show Xcode version
      run: xcodebuild -version
      
    - name: Cache SPM dependencies
      uses: actions/cache@v3
      with:
        path: |
          Tocik/Tocik/Build
          ~/Library/Developer/Xcode/DerivedData
        key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-spm-
          
    - name: Install dependencies
      working-directory: Tocik/Tocik
      run: |
        # 如果使用 CocoaPods，取消下面的注释
        # pod install
        echo "No dependencies to install"
        
    - name: Build for iOS
      working-directory: Tocik/Tocik
      run: |
        # 构建项目（不签名）
        xcodebuild \
          -project Tocik.xcodeproj \
          -scheme Tocik \
          -configuration Release \
          -sdk iphoneos \
          -destination 'generic/platform=iOS' \
          -archivePath $PWD/build/Tocik.xcarchive \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO \
          clean archive
          
    - name: Export IPA (Unsigned)
      working-directory: Tocik/Tocik
      run: |
        # 创建 exportOptions.plist
        cat > exportOptions.plist <<EOF
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
          <key>method</key>
          <string>development</string>
          <key>compileBitcode</key>
          <false/>
          <key>signingStyle</key>
          <string>manual</string>
          <key>stripSwiftSymbols</key>
          <true/>
          <key>thinning</key>
          <string>&lt;none&gt;</string>
        </dict>
        </plist>
        EOF
        
        # 导出 IPA（尝试不签名导出）
        # 注意：标准的 xcodebuild export 需要签名，所以我们直接从 archive 中提取
        
        # 创建输出目录
        mkdir -p build/IPA
        
        # 从 archive 中提取 app
        cp -r build/Tocik.xcarchive/Products/Applications/Tocik.app build/IPA/Payload/Tocik.app || mkdir -p build/IPA/Payload && cp -r build/Tocik.xcarchive/Products/Applications/Tocik.app build/IPA/Payload/
        
        # 打包成 IPA
        cd build/IPA
        zip -r ../../Tocik-unsigned.ipa Payload
        cd ../..
        
    - name: Get version info
      id: version
      working-directory: Tocik/Tocik
      run: |
        # 从 Xcode 项目获取版本号
        VERSION=$(xcodebuild -project Tocik.xcodeproj -showBuildSettings | grep -m 1 'MARKETING_VERSION' | awk '{print $3}')
        BUILD=$(xcodebuild -project Tocik.xcodeproj -showBuildSettings | grep -m 1 'CURRENT_PROJECT_VERSION' | awk '{print $3}')
        
        if [ -z "$VERSION" ]; then
          VERSION="4.0.0"
        fi
        if [ -z "$BUILD" ]; then
          BUILD="1"
        fi
        
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "build=$BUILD" >> $GITHUB_OUTPUT
        echo "App Version: $VERSION ($BUILD)"
        
    - name: Rename IPA with version
      working-directory: Tocik/Tocik
      run: |
        VERSION="${{ steps.version.outputs.version }}"
        BUILD="${{ steps.version.outputs.build }}"
        mv Tocik-unsigned.ipa "Tocik-v${VERSION}-build${BUILD}-unsigned.ipa"
        
    - name: Upload IPA as artifact
      uses: actions/upload-artifact@v4
      with:
        name: Tocik-IPA
        path: Tocik/Tocik/Tocik-v*.ipa
        retention-days: 30
        
    - name: Create Release (on tag)
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: Tocik/Tocik/Tocik-v*.ipa
        draft: false
        prerelease: false
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Upload build log on failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: build-logs
        path: |
          Tocik/Tocik/build/*.log
          ~/Library/Logs/DiagnosticReports/*
        retention-days: 7

